#!/usr/bin/env python3
"""Render the in-app copy of the Traditional-to-Simplified fold table (AQ-02 P2b).

Text normalization v3 folds Chinese Traditional characters to Simplified with
the committed table `config/language-normalization/hant-hans-v1.txt`. The Swift
verifier embeds the table's exact bytes in a generated source, so the app and
`scripts/lib/language_metrics.py` fold the same characters and never read the
OS's ICU data, which moves with the OS. The table must pass its integrity check
(`language_metrics.fold_table_issues`) before it is rendered.

    python3 scripts/generate_hant_hans_fold_swift.py           rewrite the Swift source
    python3 scripts/generate_hant_hans_fold_swift.py --check   fail when it is stale

`scripts/dev.sh regen` runs it; the contract gate runs `--check`.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))

from lib import language_metrics  # noqa: E402


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = Path("Sources/SharedSupport/Services/HantHansFoldTable.swift")
STALE_MESSAGE = "HantHansFoldTable.swift is stale"


def render() -> str:
    """The generated Swift source for the committed table."""
    table = language_metrics.HANT_HANS_TABLE
    manifest_path = language_metrics.HANT_HANS_MANIFEST
    data = table.read_bytes()
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if issues := language_metrics.fold_table_issues(data, manifest):
        raise ValueError(f"{table.name} fails its integrity check: {', '.join(issues)}")
    table_path = table.relative_to(ROOT).as_posix()
    manifest_relative = manifest_path.relative_to(ROOT).as_posix()
    body = "".join(f"    {line}\n" for line in data.decode("ascii").splitlines())
    return (
        f"// Generated by scripts/generate_hant_hans_fold_swift.py from {table_path}.\n"
        "// Do not edit: a new table is a new versioned file and a new text normalization version;\n"
        "// regenerate with `scripts/dev.sh regen`.\n"
        "\n"
        "/// The Traditional-to-Simplified Chinese fold of text normalization v3 (AQ-02 P2b), the\n"
        "/// exact bytes of the committed table that `scripts/lib/language_metrics.py` folds with, so\n"
        "/// the in-app verifier never depends on the OS's ICU data. Each line maps one source code\n"
        "/// point to one target code point (uppercase hexadecimal); no target is itself a source.\n"
        "/// Derived from ICU's `Hant-Hans` transform; Unicode License v3. Provenance, license and\n"
        f"/// SHA-256: `{manifest_relative}`.\n"
        "enum HantHansFoldTable {\n"
        f"    static let version = \"{manifest['id']}\"\n"
        f"    static let tableSHA256 = \"{manifest['sha256']}\"\n"
        f"    static let entryCount = {manifest['entryCount']}\n"
        "    static let table = \"\"\"\n"
        f"{body}"
        "\n"
        "    \"\"\"\n"
        "}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail when the generated source is stale")
    args = parser.parse_args()
    output = ROOT / OUTPUT
    try:
        expected = render()
    except (OSError, ValueError, KeyError, json.JSONDecodeError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    if args.check:
        actual = output.read_text(encoding="utf-8") if output.is_file() else ""
        if actual != expected:
            print(f"error: {STALE_MESSAGE}; run: python3 scripts/generate_hant_hans_fold_swift.py",
                  file=sys.stderr)
            return 1
        print("HantHansFoldTable.swift: fresh")
        return 0
    temporary = output.with_name(f"{output.name}.tmp.{os.getpid()}")
    temporary.write_text(expected, encoding="utf-8")
    os.replace(temporary, output)
    print(f"Rendered {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
