#!/usr/bin/env python3
"""Generate the README performance charts as deterministic SVGs.

Reads tracked benchmark registry records and emits dark + light SVG variants
under docs/charts/. Output is byte-deterministic (no timestamps, fixed float
formatting), so `--check` can fail-close on staleness exactly like the other
derived artifacts. Python stdlib only — no plotting dependency joins the
toolchain for this.

Data provenance:
  - The RTF chart reads the newest canonical macOS ui-generation record
    (RTF_RECORD) and `--check` fails when a newer canonical record for the same
    hardware exists, so the pin cannot silently age. RTF is the standard
    real-time factor (generation seconds per audio second, lower is faster).
    A record published before the 2026-09-12 cutover stores the inverted
    decode-loop speedup under `rtf`; for those the chart derives a standard
    value from each take's app submit→completed span (scripts/lib/rtf.py) and
    says so in its footer. The README alt text is generated from the same
    numbers between the markers in README.md, so prose cannot drift from the
    drawing. The retired gate-delta chart's pinned A/B pair remains history in
    benchmarks/HISTORY.md and OPTIMIZATION.md §K; it is never re-promoted to a
    chart (technical sections are maintained whole-package surfaces).
  - The long-form memory chart embeds the per-segment table from the local
    lane evidence run named in LONGFORM_RUN_ID (smoke lane
    `--long-form-segments 10`; lane evidence is never a registry record, so
    the privacy-safe numbers are pinned here with their run ID).

Usage:
  python3 scripts/generate_readme_charts.py            # rebuild
  python3 scripts/generate_readme_charts.py --check    # fail if stale
"""

from __future__ import annotations

import argparse
import json
import re
import statistics
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = ROOT / "docs" / "charts"
README_PATH = ROOT / "README.md"
RECORDS_DIR = ROOT / "benchmarks" / "runs" / "ui-generation"
README_MARKERS = ("<!-- rtf-chart:start (generated by scripts/generate_readme_charts.py) -->",
                  "<!-- rtf-chart:end -->")
if str(ROOT / "scripts") not in sys.path:
    sys.path.insert(0, str(ROOT / "scripts"))
from lib import rtf as rtf_semantics  # noqa: E402

# Newest canonical macOS UI matrix on the canonical hardware profile.
# `--check` refuses a stale pin (see newest_canonical_record).
RTF_RECORD = "macos-xcui-benchmark-20260905-012117-0b234262"
RTF_HARDWARE_PROFILE = "mac-mini-m2-8gb"
LONGFORM_RUN_ID = "macos-xcui-smoke-20260725-062451-8f15c1fd"
# (audio seconds, engine phys-footprint end MB, peak MB) per segment.
LONGFORM_SEGMENTS = (
    (49.9, 2454.7, 3037.4),
    (53.0, 2479.2, 2995.3),
    (61.1, 2507.0, 3040.3),
    (57.4, 2486.4, 3040.2),
    (57.6, 2505.5, 3040.8),
    (48.7, 2301.5, 3040.1),
    (55.8, 2476.3, 3040.9),
    (60.6, 2490.3, 3042.4),
    (56.6, 2302.3, 3041.5),
    (53.3, 2480.9, 3041.1),
    (54.7, 2505.8, 3041.6),
    (17.2, 2427.0, 2952.1),
)

MODES = ("custom", "design", "clone")
MODE_LABELS = {"custom": "Built-in Voice", "design": "Voice Design", "clone": "Voice Cloning"}
LENGTHS = ("short", "medium", "long")

# Palette validated with the dataviz six-checks validator against each
# surface (brand hue families deepened until every check passed).
THEMES = {
    "dark": {
        "ink": "#e6edf3",
        "muted": "#9198a1",
        "grid": "#30363d",
        "modes": {"custom": "#BE8A24", "design": "#9070E6", "clone": "#E26034"},
        "series": ("#9070E6", "#E26034"),
        "pre_bar": "#484f58",
        "box_fill": "#161b22",
    },
    "light": {
        "ink": "#1f2328",
        "muted": "#656d76",
        "grid": "#d1d9e0",
        "modes": {"custom": "#8A6410", "design": "#6C47C8", "clone": "#B4471B"},
        "series": ("#6C47C8", "#B4471B"),
        "pre_bar": "#afb8c1",
        "box_fill": "#f6f8fa",
    },
}

FONT = "-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif"


def load_record(record_id: str) -> dict:
    path = RECORDS_DIR / f"{record_id}.json"
    return json.loads(path.read_text(encoding="utf-8"))


def load_rtf_medians(record_id: str) -> tuple[dict[str, float], bool]:
    """Per-cell median standard RTF and whether it was derived from a legacy record."""
    payload = load_record(record_id)
    per_cell: dict[str, list[float]] = {}
    derived = not rtf_semantics.is_standard(payload)
    for take in payload["takes"]:
        value, _ = rtf_semantics.take_rtf(payload, take)
        if value is None:
            raise SystemExit(f"error: {record_id} take {take.get('cell')} has no standard RTF")
        per_cell.setdefault(re.sub(r"#\d+$", "", take["cell"]), []).append(value)
    return {key: statistics.median(values) for key, values in per_cell.items()}, derived


def newest_canonical_record() -> str:
    """Run id of the newest canonical macOS ui-generation record on the chart hardware."""
    candidates: list[tuple[str, str]] = []
    for path in RECORDS_DIR.glob("macos-*.json"):
        payload = json.loads(path.read_text(encoding="utf-8"))
        run = payload["run"]
        if (
            run.get("classification") == "canonical"
            and payload.get("hardware", {}).get("profileID") == RTF_HARDWARE_PROFILE
        ):
            candidates.append((run["finishedAt"], run["id"]))
    if not candidates:
        raise SystemExit("error: no canonical macOS ui-generation record found")
    return max(candidates)[1]


def readme_alt_text(medians: dict[str, float]) -> str:
    parts = []
    for mode in MODES:
        values = [medians[f"{mode}/{length}/warm"] for length in LENGTHS]
        parts.append(f"{MODE_LABELS[mode]} {min(values):.2f} to {max(values):.2f}")
    return (
        "Grouped bar chart: warm real-time factor by script length, lower is faster: "
        + ", ".join(parts)
        + ". Every bar sits below the real-time line at 1.0."
    )


def readme_block(medians: dict[str, float]) -> str:
    alt = readme_alt_text(medians)
    return "\n".join([
        README_MARKERS[0],
        "<picture>",
        '  <source media="(prefers-color-scheme: dark)" srcset="docs/charts/rtf-by-mode-dark.svg">',
        f'  <img alt="{alt}" src="docs/charts/rtf-by-mode-light.svg">',
        "</picture>",
        README_MARKERS[1],
    ])


def render_readme(medians: dict[str, float]) -> str:
    text = README_PATH.read_text(encoding="utf-8")
    start, end = README_MARKERS
    if text.count(start) != 1 or text.count(end) != 1:
        raise SystemExit("error: README.md must contain exactly one rtf-chart marker pair")
    head, rest = text.split(start, 1)
    _, tail = rest.split(end, 1)
    return head + readme_block(medians) + tail


def svg_open(width: int, height: int) -> list[str]:
    return [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}" role="img">',
        f'<g font-family="{FONT}">',
    ]


def text(x: float, y: float, value: str, *, fill: str, size: int = 12,
         weight: str = "normal", anchor: str = "start") -> str:
    return (
        f'<text x="{x:.1f}" y="{y:.1f}" fill="{fill}" font-size="{size}" '
        f'font-weight="{weight}" text-anchor="{anchor}">{value}</text>'
    )


def rtf_chart(theme_name: str) -> str:
    theme = THEMES[theme_name]
    medians, derived = load_rtf_medians(RTF_RECORD)
    width, height = 720, 440
    left, right, top = 110.0, 84.0, 64.0
    x0, x1 = left, width - right
    scale_max = 1.2

    def x_for(value: float) -> float:
        return x0 + (x1 - x0) * min(value, scale_max) / scale_max

    parts = svg_open(width, height)
    parts.append(text(16, 28, "Faster than playback in every mode", fill=theme["ink"], size=16, weight="600"))
    parts.append(text(16, 47, "Warm real-time factor: seconds of generation per second of audio (lower is faster) · Mac mini M2, 8 GB",
                      fill=theme["muted"], size=12))

    bar_h, in_gap, group_gap = 16.0, 6.0, 26.0
    y = top + 14.0
    for grid_value in (0.25, 0.5, 0.75, 1.0):
        gx = x_for(grid_value)
        emphasized = grid_value == 1.0
        stroke = theme["muted"] if emphasized else theme["grid"]
        dash = "" if emphasized else ' stroke-dasharray="3 3"'
        parts.append(
            f'<line x1="{gx:.1f}" y1="{top:.1f}" x2="{gx:.1f}" y2="{height - 52}" '
            f'stroke="{stroke}" stroke-width="1"{dash}/>'
        )
        label = "1.0 · realtime" if emphasized else f"{grid_value:.2f}"
        parts.append(text(gx, height - 34, label, fill=theme["muted"], size=11, anchor="middle"))

    for mode in MODES:
        color = theme["modes"][mode]
        parts.append(f'<circle cx="{22}" cy="{y + 2:.1f}" r="5" fill="{color}"/>')
        parts.append(text(32, y + 6, MODE_LABELS[mode], fill=theme["ink"], size=13, weight="600"))
        y += 16.0
        for length in LENGTHS:
            value = medians[f"{mode}/{length}/warm"]
            bw = x_for(value) - x0
            parts.append(text(x0 - 8, y + bar_h - 4, length, fill=theme["muted"], size=11, anchor="end"))
            parts.append(
                f'<path d="M{x0:.1f} {y:.1f} h{bw - 4:.1f} a4 4 0 0 1 4 4 v{bar_h - 8:.1f} '
                f'a4 4 0 0 1 -4 4 h-{bw - 4:.1f} z" fill="{color}"/>'
            )
            parts.append(text(x0 + bw + 6, y + bar_h - 4, f"{value:.2f}", fill=theme["ink"], size=11))
            y += bar_h + in_gap
        y += group_gap - in_gap
    if derived:
        parts.append(text(16, height - 6,
                          "RTF derived from each take's app submit→completed span (record predates the 2026-09-12 RTF cutover)",
                          fill=theme["muted"], size=10))
    parts.append(text(width - 16, height - 6,
                      f"record {RTF_RECORD[-8:]} · benchmarks/HISTORY.md",
                      fill=theme["muted"], size=10, anchor="end"))
    parts.extend(("</g>", "</svg>"))
    return "\n".join(parts) + "\n"


def memory_chart(theme_name: str) -> str:
    theme = THEMES[theme_name]
    width, height = 720, 340
    left, right, top, bottom = 64.0, 44.0, 72.0, 58.0
    x0, x1 = left, width - right
    y0, y1 = float(height - bottom), top
    y_max = 3200.0
    count = len(LONGFORM_SEGMENTS)

    def x_for(index: int) -> float:
        return x0 + (x1 - x0) * index / (count - 1)

    def y_for(mb: float) -> float:
        return y0 - (y0 - y1) * mb / y_max

    ends = [row[1] for row in LONGFORM_SEGMENTS]
    peaks = [row[2] for row in LONGFORM_SEGMENTS]
    growth = 100.0 * (ends[-1] - ends[0]) / ends[0]
    cumulative: list[float] = []
    running = 0.0
    for row in LONGFORM_SEGMENTS:
        running += row[0]
        cumulative.append(running)

    parts = svg_open(width, height)
    parts.append(text(16, 28, "Memory stays flat at audiobook scale", fill=theme["ink"], size=16, weight="600"))
    parts.append(text(16, 47, "Engine physical footprint across a 12-segment long-form project "
                              f"({cumulative[-1] / 60:.1f} min of audio)", fill=theme["muted"], size=12))

    for grid_mb in (1000, 2000, 3000):
        gy = y_for(grid_mb)
        parts.append(
            f'<line x1="{x0:.1f}" y1="{gy:.1f}" x2="{x1:.1f}" y2="{gy:.1f}" '
            f'stroke="{theme["grid"]}" stroke-width="1" stroke-dasharray="3 3"/>'
        )
        parts.append(text(x0 - 8, gy + 4, f"{grid_mb / 1000:.0f} GB", fill=theme["muted"], size=11, anchor="end"))
    parts.append(f'<line x1="{x0:.1f}" y1="{y0:.1f}" x2="{x1:.1f}" y2="{y0:.1f}" '
                 f'stroke="{theme["grid"]}" stroke-width="1"/>')

    series = (("peak while generating", peaks, theme["series"][1]),
              ("after each segment", ends, theme["series"][0]))
    for label, values, color in series:
        points = " ".join(f"{x_for(i):.1f},{y_for(v):.1f}" for i, v in enumerate(values))
        parts.append(f'<polyline points="{points}" fill="none" stroke="{color}" '
                     f'stroke-width="2" stroke-linejoin="round"/>')
        for i, v in enumerate(values):
            parts.append(f'<circle cx="{x_for(i):.1f}" cy="{y_for(v):.1f}" r="3" fill="{color}"/>')

    legend_x = x1 - 170.0
    for offset, (label, values, color) in enumerate(series):
        ly = 20.0 + offset * 16
        parts.append(f'<rect x="{legend_x:.1f}" y="{ly - 8:.1f}" width="10" height="10" rx="2" fill="{color}"/>')
        parts.append(text(legend_x + 16, ly + 1, label, fill=theme["muted"], size=11))

    parts.append(text(x_for(count - 1), y_for(ends[-1]) + 20, f"first→last {growth:+.1f}%",
                      fill=theme["ink"], size=11, weight="600", anchor="end"))
    for index in (0, 5, count - 1):
        anchor = "end" if index == count - 1 else ("start" if index == 0 else "middle")
        parts.append(text(x_for(index), y0 + 16, f"seg {index}", fill=theme["muted"], size=11, anchor=anchor))
        parts.append(text(x_for(index), y0 + 30, f"{cumulative[index]:.0f}s audio",
                          fill=theme["muted"], size=10, anchor=anchor))
    parts.append(text(width - 16, height - 6, f"smoke run {LONGFORM_RUN_ID[-8:]} · --long-form-segments 10",
                      fill=theme["muted"], size=10, anchor="end"))
    parts.extend(("</g>", "</svg>"))
    return "\n".join(parts) + "\n"


def architecture_chart(theme_name: str) -> str:
    theme = THEMES[theme_name]
    width, height = 720, 252
    violet = theme["modes"]["design"]
    parts = svg_open(width, height)

    def box(x: float, y: float, w: float, h: float, lines: tuple[str, ...], *,
            stroke: str, title: bool = False) -> None:
        parts.append(
            f'<rect x="{x:.1f}" y="{y:.1f}" width="{w:.1f}" height="{h:.1f}" rx="8" '
            f'fill="{theme["box_fill"]}" stroke="{stroke}" stroke-width="1.5"/>'
        )
        line_height = 16.0
        start = y + h / 2 - line_height * (len(lines) - 1) / 2 + 4.5
        for index, label in enumerate(lines):
            weight = "600" if title and index == 0 else "normal"
            fill = theme["ink"] if index == 0 else theme["muted"]
            parts.append(text(x + w / 2, start + index * line_height, label,
                              fill=fill, size=12, weight=weight, anchor="middle"))

    def arrow(x1: float, y1: float, x2: float, y2: float) -> None:
        parts.append(f'<line x1="{x1:.1f}" y1="{y1:.1f}" x2="{x2:.1f}" y2="{y2:.1f}" '
                     f'stroke="{theme["muted"]}" stroke-width="1.5"/>')
        if x2 > x1:  # rightward head
            parts.append(f'<path d="M{x2:.1f} {y2:.1f} l-7 -4 v8 z" fill="{theme["muted"]}"/>')
        elif y2 > y1:  # downward head
            parts.append(f'<path d="M{x2:.1f} {y2:.1f} l-4 -7 h8 z" fill="{theme["muted"]}"/>')
        else:  # upward head
            parts.append(f'<path d="M{x2:.1f} {y2:.1f} l-4 7 h8 z" fill="{theme["muted"]}"/>')

    # Owned-runtime group.
    parts.append(
        f'<rect x="356" y="30" width="348" height="164" rx="10" fill="{violet}" '
        f'fill-opacity="0.07" stroke="{violet}" stroke-width="1.5"/>'
    )
    parts.append(text(372, 50, "VocelloQwen3Core", fill=violet, size=12, weight="600"))
    parts.append(text(496, 50, "· the owned runtime", fill=theme["muted"], size=11))

    box(16, 84, 116, 44, ("SwiftUI app",), stroke=theme["grid"], title=True)
    box(180, 84, 132, 44, ("Engine service", "separate process"), stroke=theme["grid"], title=True)
    box(372, 62, 128, 52, ("Engine actor", "owns each session"), stroke=theme["grid"], title=True)
    box(532, 62, 156, 52, ("Qwen3-TTS talker", "+ code predictor"), stroke=theme["grid"], title=True)
    box(532, 128, 156, 48, ("Mimi decoder", "streams audio"), stroke=theme["grid"], title=True)
    box(372, 128, 128, 48, ("MLX · Metal", "unified memory"), stroke=theme["grid"], title=True)

    arrow(132, 106, 176, 106)
    parts.append(text(154, 76, "XPC", fill=theme["muted"], size=11, anchor="middle"))
    arrow(312, 106, 368, 106)
    arrow(500, 88, 528, 88)
    arrow(610, 114, 610, 124)
    # Talker and decoder execute on MLX (plain connector, no direction).
    parts.append(f'<line x1="500" y1="152" x2="528" y2="152" '
                 f'stroke="{theme["muted"]}" stroke-width="1.5" stroke-dasharray="3 3"/>')

    # Streaming return path: decoder → app, chunk by chunk.
    parts.append(
        f'<path d="M610 176 v46 h-536 v-83" fill="none" stroke="{violet}" stroke-width="1.5"/>'
    )
    parts.append(f'<path d="M74 132 l-4 7 h8 z" fill="{violet}"/>')
    parts.append(text(360, 240, "PCM audio streams back chunk by chunk — playback starts before generation finishes",
                      fill=theme["muted"], size=11, anchor="middle"))
    parts.extend(("</g>", "</svg>"))
    return "\n".join(parts) + "\n"


CHARTS = {
    "architecture": architecture_chart,
    "rtf-by-mode": rtf_chart,
    "longform-memory": memory_chart,
}


def render_all() -> dict[str, str]:
    rendered: dict[str, str] = {}
    for chart_name, renderer in sorted(CHARTS.items()):
        for theme_name in ("dark", "light"):
            rendered[f"{chart_name}-{theme_name}.svg"] = renderer(theme_name)
    return rendered


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if committed charts are stale")
    args = parser.parse_args()

    newest = newest_canonical_record()
    if newest != RTF_RECORD:
        print(
            f"error: RTF_RECORD pins {RTF_RECORD} but the newest canonical record is {newest}; "
            "update the pin in scripts/generate_readme_charts.py and website/src/sections/Engineering.jsx",
            file=sys.stderr,
        )
        return 1
    rendered = render_all()
    medians, _ = load_rtf_medians(RTF_RECORD)
    readme = render_readme(medians)
    if args.check:
        stale = [
            name for name, content in rendered.items()
            if not (OUTPUT_DIR / name).is_file()
            or (OUTPUT_DIR / name).read_text(encoding="utf-8") != content
        ]
        if README_PATH.read_text(encoding="utf-8") != readme:
            stale.append("README.md (rtf-chart block)")
        if stale:
            print(f"error: README charts are stale: {', '.join(sorted(stale))}", file=sys.stderr)
            print("run: python3 scripts/generate_readme_charts.py", file=sys.stderr)
            return 1
        print(f"README charts: fresh ({len(rendered)} files + README block)")
        return 0

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for name, content in sorted(rendered.items()):
        (OUTPUT_DIR / name).write_text(content, encoding="utf-8")
    README_PATH.write_text(readme, encoding="utf-8")
    print(f"Rendered {len(rendered)} chart files → {OUTPUT_DIR.relative_to(ROOT)} and the README rtf-chart block")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
